family_main_cookie_hideSidebar:
    pattern:  /cookie/hideSidebar
    defaults: { _controller: FamilyMainBundle:Ajax:cookieHideSidebar }

family_main_relation_delete:
    pattern: /relation/delete
    defaults: { _controller: FamilyMainBundle:Ajax:deleteRelation }

family_main_family_sort:
    pattern:  /famille/{id}/sort
    defaults: { _controller: FamilyMainBundle:Ajax:familySort }
    requirements:
        id:  \d+

family_main_sidebar_search:
    pattern:  /sidebar/search
    defaults: { _controller: FamilyMainBundle:Ajax:sidebarSearch }