parameters:
#    family_main.example.class: Family\Bundle\MainBundle\Example

services:
#    family_main.example:
#        class: %family_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
