parameters:
#    family_tree.example.class: Family\Bundle\TreeBundle\Example

services:
#    family_tree.example:
#        class: %family_tree.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
