parameters:
#    family_user.example.class: Family\Bundle\UserBundle\Example

services:
#    family_user.example:
#        class: %family_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
