<?php

namespace Family\Bundle\TreeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
	public function findByFamilyOrderedByName($familyId)
    {
        $query = $this->createQueryBuilder('p')
	        ->where('p.family = :id')
	        ->orderBy('p.lastName, p.firstName', 'ASC')
	        ->setParameter('id', $familyId)
	        ->getQuery();
        return $query->getResult();
	}

	public function findByFamilyOrderedBySurname($familyId)
    {
        $query = $this->createQueryBuilder('p')
	        ->where('p.family = :id')
	        ->orderBy('p.firstName, p.lastName', 'ASC')
	        ->setParameter('id', $familyId)
	        ->getQuery();
        return $query->getResult();
	}

	public function findByFamilyOrderedByBirthdate($familyId)
    {
        $query = $this->createQueryBuilder('p')
	        ->where('p.family = :id')
	        ->orderBy('p.birthDate', 'ASC')
	        ->setParameter('id', $familyId)
	        ->getQuery();
        return $query->getResult();
	}
}
