<?php

namespace Family\Bundle\TreeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationRepository extends EntityRepository
{
}
