<?php

namespace Family\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamilyAccessCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyAccessCodeRepository extends EntityRepository
{
}
